// Generated by CoffeeScript 1.9.3
(function() {
  var Hapi, caching, engine, faker, good, path, react, server;

  Hapi = require('hapi');

  react = require('react');

  engine = require('hapijs-react-views')();

  faker = require('faker');

  good = require('good');

  path = require('path');

  server = new Hapi.Server();

  server.connection({
    host: 'localhost',
    port: 8000
  });

  process.env.NODE_ENV = process.env.NODE_ENV || 'development';

  if (process.env.NODE_ENV === 'development') {
    caching = false;
  }

  server.views({
    defaultExtension: 'jsx',
    engines: {
      jsx: engine
    },
    path: path.join(__dirname, 'views'),
    isCached: caching
  });

  server.route({
    method: 'GET',
    path: '/',
    handler: (function(_this) {
      return function(request, reply) {
        return reply.view('index', {
          title: 'world'
        });
      };
    })(this)
  });

  server.route({
    method: 'GET',
    path: '/js/react-with-addons.js',
    handler: (function(_this) {
      return function(request, reply) {
        return reply.file('./vendors/react/react-with-addons.js');
      };
    })(this)
  });

  server.route({
    method: 'GET',
    path: '/js/JSXTransformer.js',
    handler: (function(_this) {
      return function(request, reply) {
        return reply.file('./vendors/react/JSXTransformer.js');
      };
    })(this)
  });

  server.route({
    method: 'GET',
    path: '/css/main.css',
    handler: (function(_this) {
      return function(request, reply) {
        return reply.file('./assets/css/main.css');
      };
    })(this)
  });

  server.register({
    register: good,
    options: {
      reporters: [
        {
          reporter: require('good-console'),
          events: {
            response: '*',
            log: '*'
          }
        }
      ]
    }
  }, (function(_this) {
    return function(err) {
      if (err) {
        throw err;
      }
    };
  })(this), server.start((function(_this) {
    return function() {
      return server.log('info', 'Server running at: ' + server.info.uri);
    };
  })(this)));

}).call(this);
